version: '3.7'

services:
  web:
    image: "web"
    container_name: "web_auction"
    build: MyAwesomePythonProject
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./MyAwesomePythonProject/:/app/
    ports:
      - 8000:8000
    env_file:
      - MyAwesomePythonProject/.env.dev