version: 2
jobs:
  build:
    docker:
      - image:  circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker login and pull base images
          command: |
            docker login -u "mr1marozik" -p "bender1591103ASAS"
      - run:
          name: Build main images
          command: |
            docker-compose -f docker-compose.prod.yml up --build -d
            docker tag web_prod:1.0  "mr1marozik/web_prod:1.0"
            docker push "mr1marozik/web_prod:1.0"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
     
